/**
 * Report reads. Every query here has a matching composite index generated by
 * scripts/gen-indexes.mjs — keep the two in step. Every query is limited to
 * the reports the person may see (ReportScope, mirroring firestore.rules).
 */

import {
  collection,
  doc,
  limit,
  onSnapshot,
  orderBy,
  query,
  where,
  type QueryConstraint,
  type Unsubscribe,
} from 'firebase/firestore';

import { firebase } from '@/lib/firebase';
import { COLLECTIONS, type Tier } from '@/shared/constants';
import { queryToken } from '@/shared/search';
import type { ReportDoc, WithId } from '@/shared/types';
import { count, fetchPage, type Cursor, type Page } from './query';
import { scopeConstraints, type ReportScope } from './scope';

export type ReportSort = 'priority' | 'newest';
export type ReportView = 'active' | 'review' | 'processing' | 'archived' | 'mine';

export interface ReportFilters {
  view: ReportView;
  tier: Tier | null;
  installationId: string | null;
  search: string;
  sort: ReportSort;
}

export const DEFAULT_FILTERS: ReportFilters = {
  view: 'active',
  tier: null,
  installationId: null,
  search: '',
  sort: 'priority',
};

const reports = () => collection(firebase.db, COLLECTIONS.reports);

/**
 * The constraints for a register view. Search narrows to newest-first and
 * ignores the review queue — that is the combination the indexes cover (see
 * gen-indexes.mjs), and the UI reflects the same rule.
 */
export function registerConstraints(f: ReportFilters, uid: string, scope: ReportScope): QueryConstraint[] {
  const scoped = scopeConstraints(scope);
  switch (f.view) {
    case 'archived':
      return [where('archived', '==', true), ...scoped, orderBy('createdAt', 'desc')];
    case 'mine':
      return [where('reportedBy', '==', uid), orderBy('createdAt', 'desc')];
    case 'processing':
      return [
        where('archived', '==', false),
        where('status', 'in', ['pending', 'failed']),
        ...scoped,
        orderBy('createdAt', 'desc'),
      ];
    default:
      break;
  }

  const token = queryToken(f.search);
  const c: QueryConstraint[] = [where('archived', '==', false), where('status', '==', 'scored'), ...scoped];
  if (f.tier) c.push(where('tier', '==', f.tier));
  // A manager's scope already fixes the installation.
  if (f.installationId && scope.kind !== 'installation') c.push(where('installationId', '==', f.installationId));
  if (token) {
    c.push(where('searchTokens', 'array-contains', token), orderBy('createdAt', 'desc'));
    return c;
  }
  if (f.view === 'review') c.push(where('verdictDecision', '==', null));
  if (f.sort === 'priority') c.push(orderBy('score', 'desc'));
  c.push(orderBy('createdAt', 'desc'));
  return c;
}

export function listReports(
  f: ReportFilters,
  uid: string,
  scope: ReportScope,
  pageSize: number,
  after: Cursor,
): Promise<Page<ReportDoc>> {
  return fetchPage<ReportDoc>(query(reports(), ...registerConstraints(f, uid, scope)), pageSize, after);
}

export function watchReport(
  id: string,
  next: (report: WithId<ReportDoc> | null) => void,
  error: (err: Error) => void,
): Unsubscribe {
  return onSnapshot(
    doc(firebase.db, COLLECTIONS.reports, id),
    (snap) => next(snap.exists() ? { id: snap.id, ...(snap.data() as ReportDoc) } : null),
    error,
  );
}

/** Live list of the newest scored reports — the dashboard's feed. */
export function watchRecentReports(
  n: number,
  scope: ReportScope,
  next: (items: WithId<ReportDoc>[]) => void,
  error: (err: Error) => void,
): Unsubscribe {
  const q = query(
    reports(),
    where('archived', '==', false),
    where('status', '==', 'scored'),
    ...scopeConstraints(scope),
    orderBy('createdAt', 'desc'),
    limit(n),
  );
  return onSnapshot(q, (snap) => next(snap.docs.map((d) => ({ id: d.id, ...(d.data() as ReportDoc) }))), error);
}

export interface RegisterCounts {
  active: number;
  tier1: number;
  tier2: number;
  tier3: number;
  awaitingReview: number;
  processing: number;
}

/** KPI counts by aggregation — no report documents are downloaded. */
export async function registerCounts(scope: ReportScope): Promise<RegisterCounts> {
  const scoped = scopeConstraints(scope);
  const base = [where('archived', '==', false), where('status', '==', 'scored'), ...scoped];
  const [active, tier1, tier2, tier3, awaitingReview, processing] = await Promise.all([
    count(query(reports(), ...base)),
    count(query(reports(), ...base, where('tier', '==', 1))),
    count(query(reports(), ...base, where('tier', '==', 2))),
    count(query(reports(), ...base, where('tier', '==', 3))),
    count(query(reports(), ...base, where('verdictDecision', '==', null))),
    count(query(reports(), where('archived', '==', false), where('status', 'in', ['pending', 'failed']), ...scoped)),
  ]);
  return { active, tier1, tier2, tier3, awaitingReview, processing };
}

/** A bounded sample for pattern analysis: the newest N scored reports. */
export async function recentScored(n: number, scope: ReportScope): Promise<WithId<ReportDoc>[]> {
  const page = await fetchPage<ReportDoc>(
    query(
      reports(),
      where('archived', '==', false),
      where('status', '==', 'scored'),
      ...scopeConstraints(scope),
      orderBy('createdAt', 'desc'),
    ),
    n,
    null,
  );
  return page.items;
}
