/* eslint-disable */
// DO NOT EDIT — generated by scripts/sync-shared.mjs from functions/src/shared/constants.ts
// Edit the canonical file and run `npm run sync`.

/**
 * Shared constants. Canonical source: functions/src/shared/ — synced verbatim
 * into src/shared/ by scripts/sync-shared.mjs. Edit here, never the copy.
 */

export const ROLES = ['reviewer', 'installation-manager', 'hse-officer', 'admin'] as const;
export type Role = (typeof ROLES)[number];

/** Least-privileged role. Every account is created with it; the rules enforce that. */
export const DEFAULT_ROLE: Role = 'reviewer';

export const ROLE_RANK: Record<Role, number> = {
  reviewer: 0,
  'installation-manager': 1,
  'hse-officer': 2,
  admin: 3,
};

export const ROLE_LABEL: Record<Role, string> = {
  reviewer: 'Reviewer',
  'installation-manager': 'Installation manager',
  'hse-officer': 'HSE officer',
  admin: 'Administrator',
};

export const ROLE_DESCRIPTION: Record<Role, string> = {
  reviewer: 'Files reports and reads the register.',
  'installation-manager': 'Owns corrective actions for an installation.',
  'hse-officer': 'Records verdicts, manages corrective actions.',
  admin: 'Manages users, roles, reference data and the audit trail.',
};

export const hasRole = (role: Role | undefined | null, min: Role): boolean =>
  ROLE_RANK[role ?? DEFAULT_ROLE] >= ROLE_RANK[min];

export const SHIFTS = ['Day', 'Night'] as const;
export type Shift = (typeof SHIFTS)[number];

export const REPORT_TYPES = ['unsafe-act', 'unsafe-condition', 'near-miss'] as const;
export type ReportType = (typeof REPORT_TYPES)[number];

export const REPORT_TYPE_LABEL: Record<ReportType, string> = {
  'unsafe-act': 'Unsafe act',
  'unsafe-condition': 'Unsafe condition',
  'near-miss': 'Near miss',
};

export const VERDICTS = ['confirmed', 'escalated', 'downgraded', 'dismissed'] as const;
export type Verdict = (typeof VERDICTS)[number];

export const VERDICT_LABEL: Record<Verdict, string> = {
  confirmed: 'Confirmed',
  escalated: 'Escalated',
  downgraded: 'Downgraded',
  dismissed: 'Dismissed',
};

export const ACTION_STATUSES = ['open', 'in_progress', 'closed', 'cancelled'] as const;
export type ActionStatus = (typeof ACTION_STATUSES)[number];

export const ACTION_STATUS_LABEL: Record<ActionStatus, string> = {
  open: 'Open',
  in_progress: 'In progress',
  closed: 'Closed',
  cancelled: 'Cancelled',
};

export const TIER_LABEL = { 1: 'Critical', 2: 'Elevated', 3: 'Controlled' } as const;
export type Tier = 1 | 2 | 3;

/** Limits enforced identically by the UI, the callables and the security rules. */
export const LIMITS = {
  reportTextMin: 12,
  reportTextMax: 4000,
  attachmentsMax: 5,
  attachmentBytesMax: 10 * 1024 * 1024,
  attachmentTypes: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'] as readonly string[],
  noteMax: 1000,
  nameMax: 80,
  /** Report submissions per user per rolling hour. */
  submitRatePerHour: 30,
  pageSize: 25,
} as const;

export const COLLECTIONS = {
  users: 'users',
  reports: 'reports',
  actions: 'actions',
  installations: 'installations',
  activities: 'activities',
  heat: 'heat',
  stats: 'stats',
  labels: 'labels',
  auditLogs: 'auditLogs',
  rateLimits: 'rateLimits',
} as const;

export const FUNCTIONS_REGION = 'asia-south1';

/**
 * Sign-in methods whose accounts count as verified without an email link:
 * Google and Apple vouch for the address, a phone number is proven by the SMS
 * code. Mirrored in firestore.rules and storage.rules (verified()).
 */
export const TRUSTED_SIGN_IN_PROVIDERS = ['google.com', 'apple.com', 'phone'] as const;
