/* eslint-disable */
// DO NOT EDIT — generated by scripts/sync-shared.mjs from functions/src/shared/search.ts
// Edit the canonical file and run `npm run sync`.

/**
 * Search tokenisation, shared by the scoring function (which writes tokens)
 * and the browser (which normalises the query the same way before querying).
 *
 * Firestore has no full-text search. The standard, cost-predictable answer is
 * an `array-contains` query over a pre-computed token array. It matches whole
 * words only, which is the honest limit of this approach — it is not fuzzy.
 */

const STOP = new Set([
  'the', 'and', 'was', 'were', 'with', 'for', 'from', 'that', 'this', 'had', 'has', 'have',
  'not', 'but', 'are', 'his', 'her', 'its', 'our', 'their', 'into', 'onto', 'while', 'when',
  'then', 'than', 'there', 'been', 'being', 'also', 'after', 'before', 'during', 'about',
]);

/** Unicode-aware, so Devanagari and Bengali words are tokens too. */
export function tokenize(text: string, max = 80): string[] {
  const out = new Set<string>();
  for (const m of String(text ?? '').toLowerCase().matchAll(/[\p{L}\p{N}][\p{L}\p{N}\p{M}-]*/gu)) {
    const t = m[0].replace(/-+$/, '');
    if (t.length < 3 || STOP.has(t)) continue;
    out.add(t);
    if (out.size >= max) break;
  }
  return [...out];
}

/** The single token a search box value is reduced to, or null if nothing usable. */
export function queryToken(input: string): string | null {
  const [first] = tokenize(input, 1);
  return first ?? null;
}
