/**
 * Copies functions/src/shared/*.ts verbatim into src/shared/ with a banner.
 *
 * The scoring engine, the validation schemas, the constants and the document
 * types exist exactly once — in functions/src/shared/ — and the browser gets a
 * byte-for-byte copy. The live preview a reporter sees and the assessment the
 * server stores cannot disagree, and neither can the form validation and the
 * server's input validation. Runs before dev and build.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const from = join(root, 'functions', 'src', 'shared');
const to = join(root, 'src', 'shared');

rmSync(to, { recursive: true, force: true });
mkdirSync(to, { recursive: true });

const files = readdirSync(from).filter((f) => f.endsWith('.ts'));
for (const f of files) {
  const banner =
    '/* eslint-disable */\n' +
    '// DO NOT EDIT — generated by scripts/sync-shared.mjs from functions/src/shared/' +
    f +
    '\n// Edit the canonical file and run `npm run sync`.\n\n';
  writeFileSync(join(to, f), banner + readFileSync(join(from, f), 'utf8'), 'utf8');
}
console.log(`sync-shared: ${files.length} file(s) -> src/shared/ (${files.join(', ')})`);
